# Generated by Django 5.0.3 on 2024-04-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chat_fav_food_chat_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
