# Generated by Django 5.0.3 on 2024-04-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_chat_color_remove_chat_fav_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fav_food',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lang',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pet',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='season',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
